version: '3.7'
services:
  replication-solr:
    image: r.ion.phx.connexta.com/replication-solr:${project.version}
    ports:
     - "8983:8983"
    volumes:
      - replication-data:/var/solr
    networks:
      - replication
  replication-rabbitmq:
    image: r.ion.phx.connexta.com/replication-rabbitmq:${project.version}
    ports:
      - "5672:5672"
    networks:
      - replication
  ion-replication:
    image: r.ion.phx.connexta.com/replication:${project.version}
    ports:
      - "8080:8080"
    networks:
      - replication
    secrets:
      - source: replication-keystore
        target: /opt/replication/config/keystores/serverKeystore.jks
      - source: replication-truststore
        target: /opt/replication/config/keystores/serverTruststore.jks
      - source: replication-ssl
        target: /opt/replication/config/ssl.properties
    configs:
      - source: replication-spring-config
        target: /opt/replication/config/application.yml
configs:
  replication-spring-config:
    external: true
secrets:
  replication-keystore:
    external: true
  replication-truststore:
    external: true
  replication-ssl:
    external: true
volumes:
  replication-data:
networks:
  replication:
